workdir:{{workdir}}
configfile:'config.yaml'



rule all:
    input:{{finaloutput}}

{% raw %}
if config['amrfinder'] == 'run_amrfinder':
    input: "{sample}/contigs.fa"
    output: "{sample}/{sample}.out"
    shell:
        """
        singularity run ~/dev/Singularity/amrfinderplus/amrfinderplus.simg amrfinder -n {input} -o {output} -t 1
        """
rule collate:
    input:expand("{sample}/{sample}.out", sample = SAMPLES)
{% endraw %}
    output:{{finaloutput}}
{% raw %}
    params:
        mduqc = config['mduqc']
        script_path = config['script_path']
    shell:
        """
        python3 {params.script_path}/collate.py {params.mduqc}
        """
{% endraw %}
