channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.9
  - pip
  - pytest
  - setuptools
  - pandas
  - libcurl
  - xlsxwriter
  - ncbi-amrfinderplus >=4
  - sourmash >=4.9.0
  - pycel
  - screed
  
