name: CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v5

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: abritamr
          environment-file: environment.yml
          miniforge-version: latest
          channels: conda-forge,bioconda
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true

      - name: Check tools
        run: |
          set +x
          python --version
          amrfinder --version
          
      - name: Install our code
        run: |
          pip install --no-deps .
          pip install pytest

      - name: Run test
        run: pytest -vvv
